# begin .github/workflows/classroom.yml
name: Autograding Tests for Assignment
on:
  - push
  - workflow_dispatch
  - repository_dispatch
jobs:
  run-autograding:
    uses: <org>/workflows-central/.github/workflows/classroom-reusable.yml@v1.0.1
    with:
      python_grader: ${{ vars.PYTHON_GRADER_081 || format('ghcr.io/{0}/python-pytest-081:latest', github.repository_owner) }}
      assignment_num: "081"

    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      NVIDIA_NIM_API_KEY: ${{ secrets.NVIDIA_NIM_API_KEY }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      DEFAULT_MODEL: ${{ secrets.DEFAULT_MODEL }}

  post-process:
    runs-on: ubuntu-latest
    needs: run-autograding
    if: always()
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: set sha
      id: set-short-sha
      run: |
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifacts-${{ env.SHORT_SHA }}
        path: artifacts

    - name: Forward feedback to summary
      run: |
        cat artifacts/feedback.md >> $GITHUB_STEP_SUMMARY

# end .github/workflows/classroom.yml
